Display an error message at start of test:sequential if json2capnp is not running
This will display that error message:

================================================================================
ERROR: json2capnp service is not running!
================================================================================

The sequential tests require the json2capnp rust server to be started.

To start the service, run the following commands:
  cd services/json2capnp
  cargo run 2000 ../../projects/test/test_cache/test

Or in a single command from the project root:
  (cd services/json2capnp && cargo run 2000 ../../projects/test/test_cache/test)

Expected service location: localhost:2000

================================================================================